version: "3"
name: "kewi-app"

services:
  app:
    container_name: app
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./app/.docker/Dockerfile
    command: [ "npm", "run", "start" ]
