version: "3"
name: "kewwie"

services: 
  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:?}
      MYSQL_DATABASE: kewwie
      MYSQL_USER: kewwie
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:?}
    ports:
      - "${DATABASE_PORT:?}:${DATABASE_PORT:?}"
    volumes:
      - ./mysql/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 15s
      retries: 10

  bot:
    container_name: bot
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./bot/.docker/Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    command: ["npm", "run", "start"]
