version: "3"
name: "spectre"

services:
  spectreapp:
    container_name: spectre-app
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./app/.docker/Dockerfile
    command: [ "npm", "run", "start" ]